apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: prompter
  namespace: prompter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prompter
    spec:
      containers:
        - name: prompter
          image: docker-registry.tools.wmflabs.org/toollabs-ruby-web:latest
          imagePullPolicy: Always
          command:
            - /app/script/server
          env:
            - name: HOME
              value: /app
            - name: PATH
              value: /ruby/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
            - name: RACK_ENV
              value: production
            - name: PORT
              value: "8000"
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: app
              mountPath: /app
            - name: ruby
              mountPath: /ruby
          workingDir: /app
      volumes:
        - name: app
          hostPath:
            path: /data/project/prompter/prompter
        - name: ruby
          hostPath:
            path: /data/project/prompter/ruby-2.4.1
